name: IC-3.7-2018-11-14
channels:
  - conda-forge
dependencies:
  - python       = 3.7
  # *REMEMBER TO CHANGE CONDA_ENV_TAG WHEN CHANGING VERSION NUMBERS*
  - cython       = 0.29
  - jupyter      = 1.0.0
  - jupyterlab   = 0.35.3
  - matplotlib   = 3.0.1
  - networkx     = 2.2
  - notebook     = 5.7.0
  - numpy        = 1.15.2
  - pandas       = 0.23.4
  - seaborn      = 0.9.0
  - pymysql      = 0.9.2
  - pytables     = 3.4.4
  - pytest       = 3.8.2
  - scipy        = 1.1.0
  - sphinx       = 1.8.1
  - tornado      = 5.1.1
  - flaky        = 3.4.0
  - hypothesis   = 3.68.0
  - pytest-xdist = 1.23.2
  - pip:
    - pytest-instafail==0.4.0
  - imagemagick
  - ffmpeg  